Dataset:
  # Preprocess data
  name: "audio_mnist"
  root_dir: "data/audio_mnist"
  add_noise: True
  background_noise_path: 'data/speech_commands_v0.02/_background_noise_'
  labels: ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]
AudioProcessing:
  # Init
  sample_rate: 16000
  augment: True

  Augmentor:
    prob: 0.8
    min_shift: -100. # ms
    max_shift: 100. # ms
    noise_prob: 0.8


  ToMelSpectrogram:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    n_mel: &n_mel 64
    n_fft: 512

  ToMFCC:
    window_size: 0.025
    window_stride: 0.01
    window: "hann"
    n_mel: *n_mel
    n_mfcc: *n_mel
    n_fft: 512

Parameters:
  num_workers: 2
  max_epochs: 35
  embedding_size: 512
  n_labels: 10
  device: 'cuda:0' #[cpu, cuda]
  batch_size: 64
  Loss_fn:
    Triplet:
      selector: 'hardest' # ['hardest', 'semi_hard', 'random', 'all']
      margin: 0.5
      classes_per_batch: 35
      samples_per_class: 5

    SoftTriplet:
      margin: 0.01
      lambda: 20
      gamma: 0.1
      tau: 0.
      centers_per_class: 5

    Triplet_Entropy:
      alpha: 0.5
      beta: 0.5
      selector: 'hardest'
      margin: 1.
      classes_per_batch: 35
      samples_per_class: 5
  Optimizer:
    name: "sgd"
    lr: 0.1
    weight_decay: 0.000001

  Scheduler:
    name: "plateau" # ["plateau", "step", "cosine"]
    step_size: 5 # {Step: 50, Plateau: 5}
    patience: 5
    gamma: 0.1
    T_max: 50



Checkpoint:
  # Checkpoint
  path: "./checkpoints/male/exp3"
  name : ""
  resume: False
